### ISSUE TITLE
Request without POST or GET 

### ISSUE THREAD

**Issue by akondasif** [ewolff/microservice-consul#8]
Hi @ewolff ,

We followed your recommendations from [this issue](https://github.com/ewolff/microservice/issues/28) and found a few instances of request method without get or post

Source:

https://github.com/ewolff/microservice-consul/blob/8631c73d86be5b0f48853591078741f371b920cf/microservice-consul-demo/microservice-consul-demo-catalog/src/main/java/com/ewolff/microservice/catalog/web/CatalogController.java#L30

and 

https://github.com/ewolff/microservice-consul/blob/8631c73d86be5b0f48853591078741f371b920cf/microservice-consul-demo/microservice-consul-demo-customer/src/main/java/com/ewolff/microservice/customer/web/CustomerController.java#L32

and 

https://github.com/ewolff/microservice-consul/blob/8631c73d86be5b0f48853591078741f371b920cf/microservice-consul-demo/microservice-consul-demo-order/src/main/java/com/ewolff/microservice/order/logic/OrderController.java#L49

**Comment by ewolff** [comment]
As mentioned https://github.com/ewolff/microservice/issues/28#issuecomment-654375293 I don't think this is a security problem. Please reopen if you have different information. Thanks.
